pr: ["master"]

jobs:
  - job:
    strategy:
      matrix:
        mac:
          imageName: 'macos-10.13'
        windows:
          imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)
    steps:
      - bash: brew install cairo
        condition: eq(variables['Agent.OS'], 'Darwin')
        displayName: Install cairo (macOS)

      - template: ci/install-rust.yml
        parameters:
          rust_version: stable

      - template: ci/test.yml
        parameters:
          toolchain: stable
          crate_path: 'druid-shell'

      - template: ci/test.yml
        parameters:
          toolchain: stable
          crate_path: '.'

      - template: ci/install-nightly.yml

      - template: ci/test.yml
        parameters:
          toolchain: nightly
          crate_path: 'druid-shell'

      - template: ci/test.yml
        parameters:
          toolchain: nightly
          crate_path: '.'
