language: rust
cache: cargo

matrix:
  include:

    - rust: stable
      name: docs
      on:
        branch: master

      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
        - cargo install-update -a

      script:
        - mdbook build docs

      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: docs/book
        keep-history: false
        on:
            branch: master
