language: rust

rust:
  - stable
  - nightly

os:
  - windows
  - osx

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

# windows builds run in git bash so these (should) Just Work
cache:
  directories:
    - $HOME/.cargo

script:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew update; brew install cairo; fi
  - export RUST_BACKTRACE=1
  - # TODO: deny warnings
  - cargo check --all || exit
  - cargo check --examples || exit
  - cargo test --all || exit
  - cargo test --examples || exit