[package]
name = "book_examples"
version = "0.1.0"
license = "Apache-2.0"
repository = "https://github.com/linebender/druid"
authors = ["Colin Rofls <colin@cmyr.net>"]
edition = "2021"
publish = false

[dependencies]
druid = { path = "../../druid", features = [ "im" ] }
im = { version = "15.1.0" }
