[package]
name = "idiopath"
version = "0.1.0"
authors = ["Raph Levien <raph@google.com>"]
edition = "2021"

[dependencies]
"druid-shell" = { path = "../druid-shell" }

futures-task = "0.3"
tokio = { version = "1", features = ["full"] }
