[package]
name = "idiopath"
version = "0.1.0"
authors = ["Raph Levien <raph@google.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.3", features = ["extension-module"] }
"druid-shell" = { path = "../druid-shell" }
