steps:
  - script: |
        cargo rustc -- -D warnings
    workingDirectory: '$(Build.SourcesDirectory)/${{parameters.crate_path}}'
    displayName: Run cargo rustc -- -D warnings on ${{parameters.crate_path}}
